version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  client:
    build: ./client
    environment:
      - REACT_APP_SERVER_URL
    ports:
      - '3000:3000'
    depends_on:
      - db

  server:
    build: ./server
    environment:
      - NODE_ENV=development
      - PHISHTANK_API_KEY
    ports:
      - '9000:9000'
    links:
      - db
    depends_on:
      - client
